#include "staticstrings.h"
#include <new>

/*********************************************************/
/*                                                       */
/*                 DO NOT EDIT THIS FILE                 */
/*              THIS FILE IS AUTO-GENERATED              */
/*                                                       */
/*  To change this file, edit staticstrings.json and/or  */
/*  staticstrigs.template.cpp, and run staticstrings.py  */
/*                                                       */
/*********************************************************/

namespace ovum
{

const StaticStringData staticStringData = {
/*@StringData@*/
};

int StaticStrings::Create(StaticStrings *&result)
{
	StaticStrings *output = new(std::nothrow) StaticStrings();
	if (output == nullptr)
		return OVUM_ERROR_NO_MEMORY;

	// StaticStringData has no default constructor, because LitString
	// has const members, so we can't use 'new' here. Since we're going
	// to copy all the string data from a static instance anyway, it's
	// probably fine to use malloc/free for this member.
	output->data = reinterpret_cast<StaticStringData*>(malloc(sizeof(StaticStringData)));
	if (output->data == nullptr)
	{
		delete output;
		return OVUM_ERROR_NO_MEMORY;
	}
	output->InitData();
	output->InitStrings();

	result = output;
	RETURN_SUCCESS;
}

StaticStrings::StaticStrings() :
	data(nullptr)
{ }

StaticStrings::~StaticStrings()
{
	free(data);
}

void StaticStrings::InitData()
{
	memcpy(this->data, &ovum::staticStringData, sizeof(StaticStringData));
}

void StaticStrings::InitStrings()
{
	StaticStringData *data = this->data;
/*@StringInitializers@*/
}

} // namespace ovum
